import { withAndroidManifest, withAppBuildGradle, withGradleProperties, withMainActivity } from '@expo/config-plugins';
import { mergeContents } from '@expo/config-plugins/build/utils/generateCode';
import type { ExpoConfig } from 'expo/config';

function env(name: string) {
  const value = process.env[name]?.trim();
  return value ? value : undefined;
}

const appVariant = env('EXPO_APP_VARIANT') ?? 'production';
const isDevelopmentVariant = appVariant === 'development';
const isFossVariant = appVariant === 'foss' || env('EXPO_PUBLIC_FOSS') === '1';
const isE2EMode = env('EXPO_PUBLIC_E2E_MODE') === '1';
const e2eServerUrl = env('EXPO_PUBLIC_E2E_SERVER_URL');
const defaultAndroidPackage = isFossVariant ? 'app.getopencode.fdroid' : 'app.getopencode';
const releaseAndroidPackage = env('EXPO_ANDROID_PACKAGE') ?? defaultAndroidPackage;
const developmentAndroidPackage = env('EXPO_ANDROID_PACKAGE_DEV') ?? `${releaseAndroidPackage}.dev`;
const androidPackage = isDevelopmentVariant ? developmentAndroidPackage : releaseAndroidPackage;
const androidReleaseBuildPropertiesPlugin: [string, { android: {
  enableMinifyInReleaseBuilds: boolean;
  enableShrinkResourcesInReleaseBuilds: boolean;
  extraProguardRules: string;
} }] = [
  'expo-build-properties',
  {
    android: {
      enableMinifyInReleaseBuilds: true,
      enableShrinkResourcesInReleaseBuilds: true,
      // Expo modules convert JS objects into native records through the Pika
      // introspection runtime and generated `$__Pika` classes, and load the
      // headless app loader by class name. R8 sees no direct references and strips
      // them, which crashed nested records (speech recognition's
      // volumeChangeEventOptions -> NullPointerException) and the headless loader
      // (ClassNotFoundException) in release builds. Costs ~33 KB of APK size.
      extraProguardRules: [
        '-keep class **$__Pika { *; }',
        '-keep class io.github.lukmccall.pika.** { *; }',
        '-keep class * implements io.github.lukmccall.pika.Introspectable { *; }',
        '-keep class expo.modules.kotlin.records.** { *; }',
        '-keep class expo.modules.adapters.react.apploader.** { *; }',
      ].join('\n'),
    },
  },
];

// The F-Droid/FOSS build drops the proprietary expo-camera (ML Kit barcode
// scanning) and expo-iap (Google Play Billing) plugins. Typed constants keep
// the tuple shape so `plugins` stays assignable to ExpoConfig.
type PluginList = NonNullable<ExpoConfig['plugins']>;
const cameraPlugin: PluginList = [['expo-camera', {
  cameraPermission: 'Allow $(PRODUCT_NAME) to scan an OpenCode pairing QR code.',
  recordAudioAndroid: false,
}]];
const iapPlugin: PluginList = ['expo-iap'];

// The Expo template defaults to -Xmx2048m -XX:MaxMetaspaceSize=512m, which OOMs
// during release AAB packaging (bundletool) with the four default ABIs. Raise
// both so `:app:packageReleaseBundle` has room. The android/ directory is
// regenerated by `expo prebuild --clean`, so this must live here, not on disk.
//
// `android.r8.optimizedResourceShrinking` opts into AGP 8.12+'s R8-integrated
// resource shrinking, which Play's "Improve your app's memory and performance
// with R8 optimization" check expects. AGP 9+ enables it by default.
const withAndroidGradleProperties = (config: ExpoConfig) =>
  withGradleProperties(config, (config) => {
    const overrides = new Set(['org.gradle.jvmargs', 'android.r8.optimizedResourceShrinking']);
    config.modResults = config.modResults.filter(
      (item) => !(item.type === 'property' && overrides.has(item.key)),
    );
    config.modResults.push({
      type: 'property',
      key: 'org.gradle.jvmargs',
      value: '-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8',
    });
    config.modResults.push({
      type: 'property',
      key: 'android.r8.optimizedResourceShrinking',
      value: 'true',
    });
    return config;
  });

// expo-camera pulls play-services-code-scanner, whose delegate activity is
// declared portrait in the library manifest. Android 16 ignores orientation
// locks on large screens, so Play flags it; override it to follow the system.
const MLKIT_SCANNER_ACTIVITY =
  'com.google.mlkit.vision.codescanner.internal.GmsBarcodeScanningDelegateActivity';

const withAndroidAppConfig = (config: ExpoConfig) => {
  const withGradle = withAndroidGradleProperties(config);
  const withManifest = withAndroidManifest(withGradle, (config) => {
    const application = config.modResults.manifest.application?.[0];
    if (application) application.$['android:usesCleartextTraffic'] = 'true';
    if (application && !isFossVariant) {
      application.activity ??= [];
      if (!application.activity.some((item) => item.$?.['android:name'] === MLKIT_SCANNER_ACTIVITY)) {
        application.activity.push({
          $: {
            'android:name': MLKIT_SCANNER_ACTIVITY,
            'android:screenOrientation': 'unspecified',
            'tools:replace': 'android:screenOrientation',
          },
        });
      }
    }
    return config;
  });

  const withActivity = withMainActivity(withManifest, (config) => {
    if (config.modResults.language !== 'kt') {
      throw new Error('The Android content-capture opt-out requires the generated Kotlin MainActivity.');
    }
    config.modResults.contents = mergeContents({
      src: config.modResults.contents,
      tag: 'opencode-disable-content-capture',
      anchor: /super\.onCreate\(null\)/,
      offset: 1,
      comment: '    //',
      newSrc: `    // Avoid content-capture accessibility traversals of large text hierarchies.
    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
      getSystemService(android.view.contentcapture.ContentCaptureManager::class.java)
        ?.setContentCaptureEnabled(false)
    }`,
    }).contents;
    return config;
  });

  if (isDevelopmentVariant) return withActivity;

  return withAppBuildGradle(withActivity, (config) => {
    const legacyFile = 'getDefaultProguardFile("proguard-android.txt")';
    const optimizedFile = 'getDefaultProguardFile("proguard-android-optimize.txt")';
    let contents = config.modResults.contents;

    // Expo's expo-router/react-native-screens pin com.google.android.material
    // 1.13.0, whose datepicker/bottomsheet internals still call the Android 15
    // deprecated statusBarColor APIs. 1.14.0 fixes them; a direct dependency
    // wins Gradle's highest-version conflict resolution without a force.
    const materialPin = "implementation 'com.google.android.material:material:1.14.0'";
    if (!contents.includes(materialPin)) {
      const anchor = 'dependencies {';
      if (!contents.includes(anchor)) {
        throw new Error('Could not find the Android app dependencies block.');
      }
      contents = contents.replace(anchor, `${anchor}\n    ${materialPin}`);
    }

    if (contents.includes(optimizedFile)) {
      config.modResults.contents = contents;
      return config;
    }
    if (!contents.includes(legacyFile)) {
      throw new Error('Could not find the Android release ProGuard default file to enable R8 optimizations.');
    }

    config.modResults.contents = contents.replace(legacyFile, optimizedFile);
    return config;
  });
};

const config: ExpoConfig = {
  name: isDevelopmentVariant ? 'OpenCode Mobile Dev' : 'OpenCode Mobile',
  slug: 'opencode-mobile',
  version: '1.0.63',
  orientation: 'default',
  icon: './assets/images/icon.png',
  scheme: 'opencodemobile',
  userInterfaceStyle: 'automatic',
  android: {
    package: androidPackage,
    versionCode: 63,
    adaptiveIcon: {
      foregroundImage: './assets/images/adaptive-icon.png',
      backgroundColor: "#202020"
    },
    predictiveBackGestureEnabled: false,
    softwareKeyboardLayoutMode: 'resize',
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  ios: {
    bundleIdentifier: isDevelopmentVariant ? 'app.getopencode.mobile.dev' : 'app.getopencode.mobile',
    buildNumber: '63',
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
      NSPhotoLibraryUsageDescription: 'Allow OpenCode Mobile to access photos you choose to attach to chat messages.',
      NSAppTransportSecurity: {
        NSAllowsArbitraryLoads: true,
      },
    },
  },
  plugins: [
    'expo-router',
    'expo-font',
    'expo-notifications',
    'expo-background-task',
    'expo-web-browser',
    ...(isFossVariant ? [] : cameraPlugin),
    [
      // Exposes the shipped app languages to the OS so iOS/Android surface the
      // correct per-app language choices. Extend both lists with every language
      // added under lib/i18n/locales.
      'expo-localization',
      {
        supportedLocales: {
          ios: ['en', 'es', 'hi', 'de', 'fr', 'zh', 'pt', 'ja'],
          android: ['en', 'es', 'hi', 'de', 'fr', 'zh', 'pt', 'ja'],
        },
      },
    ],
    ...(isDevelopmentVariant ? [] : [androidReleaseBuildPropertiesPlugin]),
    [
      'expo-speech-recognition',
      {
        microphonePermission: 'Allow $(PRODUCT_NAME) to access the microphone for voice input.',
        speechRecognitionPermission: 'Allow $(PRODUCT_NAME) to convert speech to text on your device.',
        androidSpeechServicePackages: ['com.google.android.googlequicksearchbox', 'com.google.android.as'],
      },
    ],
    [
      'expo-splash-screen',
      {
        image: './assets/images/splash-icon.png',
        imageWidth: 200,
        resizeMode: 'contain',
        backgroundColor: '#ffffff',
        dark: {
          backgroundColor: '#000000',
        },
      },
    ],
    'expo-image',
    'expo-video',
    'expo-secure-store',
    ...(isFossVariant ? [] : iapPlugin),
    'expo-status-bar',
    withAndroidAppConfig as unknown as string,
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    router: {},
    e2eMode: isE2EMode,
    e2eServerUrl,
    foss: isFossVariant,
    updates: {
      enabled: !isDevelopmentVariant && !isFossVariant && !isE2EMode,
      testing: isDevelopmentVariant && isE2EMode,
      appStoreId: env('EXPO_IOS_APP_STORE_ID'),
      appStoreCountry: env('EXPO_IOS_APP_STORE_COUNTRY'),
    },
    connectPilot: {
      testing: isDevelopmentVariant && isE2EMode,
    },
  },
};

export default config;
