import { Platform, StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  header: { elevation: 0 },
  headerMain: { flex: 1, minWidth: 0, alignSelf: 'stretch', justifyContent: 'center' },
  headerActions: { flexDirection: 'row', alignItems: 'center', flexShrink: 0 },
  headerTitle: { fontFamily: Fonts.display, fontWeight: '700' },
  headerSessionAnchor: { flex: 1, alignSelf: 'stretch', justifyContent: 'center', borderRadius: 14, marginRight: 8 },
  headerSessionAnchorPressed: { opacity: 0.82 },
  headerSessionContent: { flexDirection: 'row', alignItems: 'center', gap: 8, minWidth: 0, minHeight: 48, paddingRight: 4 },
  headerSessionTextWrap: { flex: 1, minWidth: 0 },
  sessionPickerOverlay: { ...StyleSheet.absoluteFillObject },
  sessionPickerBackdrop: { ...StyleSheet.absoluteFillObject },
  sessionPickerBackdropFill: { flex: 1, backgroundColor: 'rgba(0,0,0,0.28)' },
  sessionPickerSheet: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, overflow: 'hidden' },
  sessionPickerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1 },
  sessionPickerCloseButton: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 10, borderRadius: 999 },
  sessionPickerCloseButtonPressed: { opacity: 0.82 },
  sessionPickerCloseLabel: { fontFamily: Fonts.sans, fontSize: 15, fontWeight: '600' },
  sessionPickerList: { padding: 12, gap: 8, paddingBottom: 24 },
  sessionPickerItem: { borderRadius: 16, borderWidth: 1 },
  sessionPickerItemRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 56, paddingHorizontal: 14, paddingVertical: 12 },
  sessionPickerItemIcon: { width: 32, height: 32, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  sessionPickerItemTextWrap: { flex: 1, gap: 2 },
  sessionPickerItemTitle: { fontFamily: Fonts.sans, fontSize: 16 },
  sessionPickerItemSubtitle: { fontFamily: Fonts.sans, fontSize: 13 },
  tabsRow: { flexDirection: 'row', borderBottomWidth: 1 },
  scroll: { flex: 1 },
  content: { padding: 12, gap: 12, paddingBottom: 20 },
  noticeCard: { borderRadius: 20 },
  waitingNoticeContent: { gap: 8 },
  waitingNoticeHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  emptyCard: { borderRadius: 22 },
  emptyContent: { gap: 14 },
  emptyTitle: { fontFamily: Fonts.display, fontWeight: '700' },
  promptStack: { gap: 10 },
  promptCard: { borderWidth: 1, borderRadius: 18 },
  promptCardInner: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 14 },
  sectionStack: { gap: 12 },
  sectionCard: { borderRadius: 18 },
  sectionHeaderCard: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  paginationRow: { alignItems: 'center', paddingVertical: 4 },
  loadingRow: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingHorizontal: 8, paddingBottom: 8 },
  composer: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 24, default: 12 }),
    gap: 10,
    borderTopWidth: 1,
  },
  inputShell: { borderWidth: 1, borderRadius: 22, paddingLeft: 12, paddingRight: 6, paddingVertical: 6 },
  composerRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 4 },
  input: { flex: 1, minHeight: 22, maxHeight: 120, fontSize: 17, marginHorizontal: -4 },
  inputContentCompact: { paddingHorizontal: 0, paddingTop: 6, paddingBottom: 6, fontFamily: Fonts.sans },
  controlsRow: { flexDirection: 'row', flexWrap: 'nowrap', gap: 6, paddingHorizontal: 0, alignItems: 'center', justifyContent: 'space-between' },
  attachmentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 2 },
  attachmentChip: { alignSelf: 'flex-start' },
  conversationBanner: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 12, gap: 8 },
  conversationBannerHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  voiceStatusRow: { paddingHorizontal: 2 },
  voiceStatusChip: { alignSelf: 'flex-start' },
  composerVoiceButton: { margin: 0 },
  composerActionButton: { margin: 0 },
  diffListCardContent: { paddingHorizontal: 0, paddingVertical: 0 },
});
